### ISSUE TITLE
Does it support gigascreen?

### ISSUE THREAD

**Issue by jsmolina** [MiSTer-devel/TSConf_MiSTer#1]
I tried Mario demo, which is suposed to benefit from Gigascreen feature:
https://events.retroscene.org/files/cafe2019/gamecompo/super_mario_bros._128k.zip

But it flickers a bit more than a 'normal' speccy.

Does it have any switch or no support yet?

**Comment by sorgelig** [comment]
flickering highly depends on sync between original frame rate and HDMI frame rate if you use HDMI.
It also may depend on TV.
